### ISSUE TITLE
Upgrade React typings

### ISSUE THREAD

**Issue by trioletas** [ctco-dev/react-template#25]
`@types/react` and `@types/react-dom` should use the same major version as `react` and `react-dom` packages

**Comment by M-ZubairAhmed** [comment]
can you please elaborate on the issue description ?

**Comment by trioletas** [comment]
Sure, please see the description

**Comment by aeldar** [comment]
Closed as not actual anymore. See explanation [here](https://github.com/ctco-dev/react-template/pull/27#issuecomment-336131988)
