### ISSUE TITLE
Can we use create-react-app-rewired?

### ISSUE THREAD

**Issue by trioletas** [ctco-dev/react-template#28]
https://github.com/timarney/react-app-rewired

**Comment by aeldar** [comment]
Sounds very promising.
To answer this question I think I could try to add or reimplement the following list of features on the clean non-ejected CRA with this approach:
- [ ] typescript
- [ ] storybook
- [ ] material ui
- [ ] jest custom config (?)
  - [ ] support storybook
  - [ ] support typescript
- [ ] 12 Factor App configuration support (REACT_APP_... env variables in runtime) (?)
- [ ] deploy to azure

I marked questionable points (for me) with a question sign. Need some time to experiment with them to be sure it is possible to implement with this approach.

@trioletas please correct this list if I missed something.

**Comment by trioletas** [comment]
Yes that looks complete. Please drop deploy to Azure though, we might eventually deprecate it in favor of container based setups. Thanks!

**Comment by aeldar** [comment]
I have got some doubts regarding jest configuration. Probably it will spoil the whole idea. Will have a look tomorrow
